# Generated by Django 4.2.7 on 2024-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=127)),
                ('valume', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=127)),
            ],
        ),
    ]
